### ISSUE TITLE
edit window

### ISSUE THREAD

**Issue by zym-creaor** [meslzy/electron-as-wallpaper#3]
### **I'm currently working on a desktop calendar**

like is
![image](https://user-images.githubusercontent.com/81000110/201567690-e37afe46-2063-4816-85b0-9d74fabd0e9e.png)

**i want to double click to edit the window**

### I have two needs

1. Double click the edit window
2. The window can be dragged and resized

Can it be achieved? Thank you very much

**Comment by meslzy** [comment]
Lemme tell what really going on behind the desktop icons.

To make the electron window behind desktop icons i need to move the window to place called list view from windows api.

When i move the windows to that place u have no control with mouse or keyboard because it's focusble.

What is the solution? To make the window interact with keyboard and mouse movements u have to use windows api.

So i can't help you archive your goal, Sorry mate.

**Comment by zym-creaor** [comment]
> Lemme tell what really going on behind the desktop icons.
> 
> To make the electron window behind desktop icons i need to move the window to place called list view from windows api.
> 
> When i move the windows to that place u have no control with mouse or keyboard because it's not focusble.
> 
> What is the solution? To make the window interact with keyboard and mouse movements u have to use windows api.
> 
> So i can't help you archive your goal, Sorry mate.

It's all right, buddy You've done great

**Comment by zym-creaor** [comment]
I think it is necessary for me to learn something related to C++
